Update codehawk.properties
SonarSource/sonar-update-center-properties pull request #173
Opened 2020-11-28 16:07 UTC by SDPMLab

added new rules

2020-12-03 21:15 UTC, ganncamp requested changes

2020-12-03 21:15 UTC, ganncamp commented on codehawk.properties
> -
Don't delete the old versions. If you do, users still on 1.3 will never be prompted by the Marketplace to upgrade to your latest version

2020-12-03 21:15 UTC, ganncamp commented on codehawk.properties
> +1.4.sqVersions=[7.9,8.4.*]
This range needs to end with the current version: 8.5.1 or with 8.5.*.

2022-01-26 13:20 UTC, colin-mueller-sonarsource commented
Superseded by #187

2022-01-26 13:20 UTC, closed without merging