Release Russian pack 8.5.1
SonarSource/sonar-update-center-properties pull request #179
Opened 2020-12-17 05:28 UTC by theshadowco

small fixes

2021-01-06 19:18 UTC, ganncamp requested changes

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.2.1.sqVersions=[8.2,8.2]
FYI, no need to use range syntax when there's no range. This could be just `8.2`

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.6.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.6/sonar-l10n-ru-plugin-8.6.jar
the artifact is 404

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.2.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.2.1/sonar-l10n-ru-plugin-8.2.1.jar
404

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.1.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.1.1/sonar-l10n-ru-plugin-8.1.1.jar
404

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.0.2.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.0.2/sonar-l10n-ru-plugin-8.0.2.jar
404

2021-01-06 19:18 UTC, ganncamp commented on l10nru.properties
> +8.5.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.5.1/sonar-l10n-ru-plugin-8.5.1.jar
This one's actually 200! Woo hoo!

2021-01-07 11:34 UTC, theshadowco commented on l10nru.properties
> +8.6.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.6/sonar-l10n-ru-plugin-8.6.jar
oops :-( fixed

2021-01-07 11:34 UTC, theshadowco commented on l10nru.properties
> +8.2.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.2.1/sonar-l10n-ru-plugin-8.2.1.jar
oops :-( fixed

2021-01-07 11:34 UTC, theshadowco commented on l10nru.properties
> +8.1.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.1.1/sonar-l10n-ru-plugin-8.1.1.jar
oops :-( fixed

2021-01-07 11:34 UTC, theshadowco commented on l10nru.properties
> +8.0.2.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.0.2/sonar-l10n-ru-plugin-8.0.2.jar
oops :-( fixed

2021-01-07 11:35 UTC, theshadowco commented on l10nru.properties
> +8.5.1.downloadUrl=https://github.com/1c-syntax/sonar-l10n-ru/releases/download/v8.5.1/sonar-l10n-ru-plugin-8.5.1.jar
:-)

2021-01-07 17:10 UTC, ganncamp approved these changes

2021-01-07 17:10 UTC, merged