Update xanitizer.properties
SonarSource/sonar-update-center-properties pull request #190
Opened 2021-01-06 13:59 UTC by normanwenzel

Added version 2.2.0

2021-01-06 21:10 UTC, ganncamp requested changes

2021-01-06 21:10 UTC, ganncamp commented on xanitizer.properties
> +2.1.0.sqVersions=[7.9,8.5.*]
This should end at 8.6.

2021-01-07 07:03 UTC, normanwenzel commented on xanitizer.properties
> +2.1.0.sqVersions=[7.9,8.5.*]
DONE

2021-01-07 17:08 UTC, ganncamp approved these changes

2021-01-07 17:11 UTC, merged