New Sonar-Groovy release 1.7
SonarSource/sonar-update-center-properties pull request #221
Opened 2021-05-30 21:49 UTC by TobiX

2021-06-04 19:14 UTC, ganncamp requested changes

2021-06-04 19:14 UTC, ganncamp commented on groovy.properties
> +1.7.sqVersions=[7.9,LATEST]
this end range should be updated to the current version: 8.9

2021-06-04 19:14 UTC, ganncamp commented on groovy.properties
> +1.6.sqVersions=[7.9,8.9.*]
This should end with `LATEST`... unless you really mean to have this version marked incompatible when 9.0 comes out?

2021-06-05 05:51 UTC, TobiX commented
I'm a bit confused: I thought I would set the compatibility end range of the newest release to LATEST, so it will be automatically compatible with future versions and set the end rage of the old (now deprecated) version to the current release, so users are urged to update when installing a newer version of SonarQube. Is that not how it works?

2021-06-07 11:40 UTC, ganncamp approved these changes
Sorry. _I_ was confused. Most people add the new version at the top of the list & I didn't catch that you had done the opposite. As they say: haste makes waste.

2021-06-07 11:40 UTC, merged

2021-06-07 11:55 UTC, TobiX commented
No problem, thanks for merging!