CodeHawk V1.6
SonarSource/sonar-update-center-properties pull request #267
Opened 2022-01-27 08:08 UTC by SEPMLAB

2022-01-27 19:17 UTC, ganncamp requested changes

2022-01-27 19:17 UTC, ganncamp commented on codehawk.properties
>  1.5.description= Added new rules
Copy/paste errors? Shouldn't this section all start with 1.6? :)

2022-01-27 19:17 UTC, ganncamp commented on codehawk.properties
>  1.5.sqVersions=[7.9,LATEST]
Assuming this _is_ for 1.6, this range needs to start with 8.9. Nothing below that is supported.

2022-01-28 08:10 UTC, SEPMLAB commented
Changes were made, Thanks!
They really were copy/paste errors :))

2022-01-28 20:09 UTC, ganncamp approved these changes

2022-01-28 20:10 UTC, merged