checkstyle: update to 10.1
SonarSource/sonar-update-center-properties pull request #281
Opened 2022-04-03 20:28 UTC by muhlba91

2022-04-05 14:37 UTC, ganncamp requested changes
9.4 has been released in the interim

2022-04-05 14:38 UTC, ganncamp approved these changes

2022-04-05 15:54 UTC, muhlba91 commented
thank you for the update! :)

2022-04-07 12:51 UTC, muhlba91 commented
@ganncamp anything needed from my side to get this merged? :)

2022-04-07 13:04 UTC, merged