Remove individuals from ownership
SonarSource/sonar-update-center-properties pull request #309
Opened 2022-05-02 08:42 UTC by julien-carsique-sonarsource

According to https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2169339970/GitHub+Authentication+Authorization#CODEOWNERS, only one team can be the "owner".

2022-05-02 09:11 UTC, pierre-guillot-sonarsource requested changes
For this repository, the ownership is shared between the SonarQube team, Chris, Ann, and Colin.

I don't think it makes sense to have all PMs, as this only relates to SQ.
About Ann and Colin, we could replace them with a community-manager team, but I don't think that exists on Github (yet?).

2022-05-02 11:41 UTC, ganncamp commented
I have no opinion as long as I can make the changes I need to make, including approving my own PRs.

2022-05-02 12:18 UTC, julien-carsique-sonarsource commented
This has no impact except on the file `.github/CODEOWNERS` itself.
It's only declarative (see [the definition](https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2169339970/GitHub+Authentication+Authorization#Team-Ownership)). The rule being "one and only one owner team per repository" :) No individuals with no exception. Multiple teams to be justified and discussed.

You are free to edit the above lines of the file if you make use of the GitHub code ownership feature for the PR requests. Everything else relies on the repository permissions.

2022-05-02 12:23 UTC, ganncamp commented
@julien-carsique-sonarsource this policy you created is about _source code_ repositories. 
Is that really what this is?

2022-05-05 14:25 UTC, julien-carsique-sonarsource commented
@ganncamp The policy applies to all the non-forked repositories, regardless of their content.
I hand over to @benzonico about discussing the rule and specific cases.

2022-05-05 14:44 UTC, benzonico commented
@ganncamp Yes, I would consider this as source. That can be argued but I am not sure it is worth our time if we have no beers involved.

@pierre-guillot-sonarsource while there is contributors outside of the team, ultimately the structure and ownership of this repo belongs to the SQ team.

2022-05-05 14:49 UTC, pierre-guillot-sonarsource approved these changes

2022-05-05 14:49 UTC, merged