ibmix-aem-sonar-rules 1.2
SonarSource/sonar-update-center-properties pull request #330
Opened 2022-06-28 15:06 UTC by mgluhak

Version 1.2 release of the ibmix-aem-sonar-rules plugin

2022-06-28 18:27 UTC, ganncamp requested changes

2022-06-29 07:10 UTC, mgluhak commented on ibmixaemrules.properties
> +1.2.description=Expanded compatibility to include the LTS version
It is the only change, thanks for the suggestion. 
Could you please advise what would be the best way to handle the compatibility interval of the 1.1 version? 
I would put it as `[9.0,LATEST]`, but I read in the plugin development guide that only the most recent version can use the LATEST keyword. Should an interval with a wildcard like this `[9.0,9.*]` be used instead?

2022-06-29 13:46 UTC, mgluhak commented on ibmixaemrules.properties
> +1.2.description=Expanded compatibility to include the LTS version
Thanks for helping out. 
I've pushed the changes, but unfortunately the Travis build is failing now. When checking the build log this is reported:
`Only the latest release of plugin ibmixaemrules may depend on LATEST SonarQube`
Looks like there are some explicit checks in place for this.

2022-06-29 14:06 UTC, ganncamp commented on ibmixaemrules.properties
> +1.2.description=Expanded compatibility to include the LTS version
Aw man. I knew only one version could be compatible with `LATEST`. I didn't realize it explicitly had to be the newest (I guess by date? I'm pretty sure the version numbers are treated as strings.)
So... I'm sorry to have wasted your time. I guess you have to put it back. :(

2022-06-29 14:21 UTC, mgluhak commented on ibmixaemrules.properties
> +1.2.description=Expanded compatibility to include the LTS version
No worries :)
I've returned it now to as it originally was.

2022-06-29 14:34 UTC, ganncamp approved these changes

2022-06-29 14:34 UTC, merged