REL-2439 SonarQube 9.7
SonarSource/sonar-update-center-properties pull request #350
Opened 2022-10-17 13:54 UTC by christophelevis

2022-10-17 13:58 UTC, ganncamp requested changes

2022-10-17 13:58 UTC, ganncamp commented on update-center-source.properties
> +9.7.description=More rich descriptions and examples for Java and C# taint analysis rules, faster analysis for JavaScript PRs and Cobol, vulnerabilities in GitHub security, OWASP ASVS report, SAML con
```suggestion
9.7.description=Faster analysis for JavaScript PRs and Cobol, vulnerabilities reported in GitHub security, OWASP ASVS report, simpler SAML configuration, rules for AWS CDK in Python, taint analysis for JavaScript AWS lambdas, and more rich descriptions and examples for Java and C# taint analysis rules
```

2022-10-18 08:42 UTC, vivek-reghunath-sonarsource approved these changes
Looks good.

2022-10-18 11:02 UTC, ganncamp approved these changes

2022-10-18 12:46 UTC, merged