support sonarqube-10.1
SonarSource/sonar-update-center-properties pull request #424
Opened 2023-07-07 12:14 UTC by xuhuisheng

Hi,

sonar-l10n-zh-plugin-10.1 has been released.

The main changes is support SonarQube 10.1.

The Download link and release notes: https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-10.1/sonar-l10n-zh-plugin-10.1.jar

The SonarCloud: https://sonarcloud.io/project/overview?id=xuhuisheng_sonar-l10n-zh

Please update the market place.

Thank you

Regards

2023-07-10 23:10 UTC, xuhuisheng commented on l10nzh.properties
> +10.0.sqVersions=[10.0,10.0.*]
We should update `[10.0,10.0.*]` to `[10.0]`, so SonarQube will notice people on 10.1 to upgrade plugin. Am I right?

2023-07-11 16:28 UTC, ganncamp requested changes

2023-07-11 16:28 UTC, ganncamp commented on l10nzh.properties
> +10.0.sqVersions=[10.0,10.0.*]
No. This range should be:
`[10.0,10.1.*]`
So that people who have already upgraded to 10.0 will be alerted to upgrade the plugin.

2023-07-12 16:52 UTC, ganncamp commented on l10nzh.properties
> +10.0.sqVersions=[10.0,10.1.*]
Shoot. I was forgetting/overlooking that you keep all of your versions public. To be honest, it's really not designed (or perhaps I should say "anticipated") that there would be a plugin version per SQ version. - Which is not to imply that I think you should change how you do this. 
AND unfortunately, public versions can't have overlapping compatibility, so this has to change back to the way you had it in the first place. Just to be explicit:
YOU WERE RIGHT. I WAS WRONG. :-D

And I'm not going to make you jump through the hoop. I'll approve this and then change it back myself. 
I'm just not sure whether users on 10.1 who are using your plugin version 10.0 will be prompted to upgrade. :-/

2023-07-12 16:53 UTC, ganncamp commented on l10nzh.properties
> +10.0.sqVersions=[10.0,10.1.*]
```suggestion
10.0.sqVersions=10.0
```

2023-07-12 16:53 UTC, ganncamp approved these changes

2023-07-12 16:54 UTC, merged

2023-07-12 16:55 UTC, ganncamp commented
FYI, the metadata generation job isn't running well right now, so it will likely be a day or so before you see this in the marketplace. Thanks for your ongoing efforts on this!