Update l10nzhtw.properties
SonarSource/sonar-update-center-properties pull request #603
Opened 2024-10-21 11:14 UTC by JE-Chen

Add 1.1 version info

2024-10-21 12:46 UTC, ganncamp commented
Have you communicated with @timlee about this to get his agreement for your takeover? Or are you just taking up the mantel because you believe the project is abandoned?

2024-10-21 14:19 UTC, JE-Chen commented
> Have you communicated with @timlee about this to get his agreement for your takeover? Or are you just taking up the mantel because you believe the project is abandoned?

Yes, I have contacted Tim Lee. He is my teacher.

2024-10-21 15:08 UTC, ganncamp commented
Thanks for the confirmation @timlee! I'm happy to move forward with this.

2024-10-21 16:07 UTC, JE-Chen commented on l10nzhtw.properties
> +1.1.sqVersions=[10.7,LATEST]
Should I also make translations for versions 10.0 - 10.6? How do I test BundlesUpToDate when I add translations for older versions?

2024-10-21 17:13 UTC, ganncamp commented on l10nzhtw.properties
> +1.1.sqVersions=[10.7,LATEST]
TBH, I don't know what BundlesUpToDate is.
You _could_ make translations for the intermediate versions. But I wasn't trying to burden you with extra work. I was hinting that this 10.7 version be set to start at 10.0. Even if it's imperfect/gappy, it's better than nothing.

2024-10-22 01:24 UTC, JE-Chen commented on l10nzhtw.properties
> +1.1.sqVersions=[10.7,LATEST]
Like this?
sqVersions=[10.0,10.0.*,10.1,10.1.*,10.2,10.2.*,10.3,10.3.*, .... -10.7,LATEST]
or can I simply do this?
sqVersions=[10.*,10.*.*,LATEST]

2024-10-23 11:50 UTC, ganncamp requested changes

2024-10-23 18:23 UTC, ganncamp approved these changes

2024-10-23 18:48 UTC, ganncamp commented
FYI, this is approved, but I can't merge until the build succeeds and I'm not finding the failure reason in the logs, so I don't know (yet) how to proceed. I've asked for help & will come back to this tomorrow.

2024-10-25 17:47 UTC, ganncamp commented
I haven't forgotten this. I'm in line for the help I requested internally.

2024-10-28 17:36 UTC, ganncamp requested changes

2024-10-28 17:36 UTC, ganncamp commented on l10nzhtw.properties
> +publicVersions=1.0, 1.1
Can you remove the space here, please

2024-10-29 11:21 UTC, ganncamp approved these changes

2024-10-29 11:21 UTC, merged

2024-10-29 11:31 UTC, ganncamp commented
I have to roll this back because the metadata generation job is failing with this error:
```
[ERROR] Failed to execute goal org.sonarsource.update-center:sonar-update-center-mojo:1.32.0.2441:generate-metadata (default-cli) on project sonar-update-center-properties: Fail to execute mojo: Plugin sonar-l10n-zh-tw-plugin.jar is declared with key 'null' in its MANIFEST, but with key 'l10nzhtw' in the update center -> [Help 1]
```
And when I look at the manifest, it has only
```
Manifest-Version: 1.0
Main-Class: Main
```
Versus a much more robust manifest in the previous version's jar. Whatever changes you made to the pom, you should undo them. 
And now that I look, I see a lot more in your jar than there should be, and I also notice that your jar name doesn't have a version number in it. That may be fine for now, but what happens when you put out the next version? They'll clash. Your jar names need to be unique.

So for now, I'm going to roll this back entirely.

2024-10-29 14:35 UTC, JE-Chen commented
> I have to roll this back because the metadata generation job is failing with this error:
> 
> ```
> [ERROR] Failed to execute goal org.sonarsource.update-center:sonar-update-center-mojo:1.32.0.2441:generate-metadata (default-cli) on project sonar-update-center-properties: Fail to execute mojo: Plugin sonar-l10n-zh-tw-plugin.jar is declared with key 'null' in its MANIFEST, but with key 'l10nzhtw' in the update center -> [Help 1]
> ```
> 
> And when I look at the manifest, it has only
> 
> ```
> Manifest-Version: 1.0
> Main-Class: Main
> ```
> 
> Versus a much more robust manifest in the previous version's jar. Whatever changes you made to the pom, you should undo them. And now that I look, I see a lot more in your jar than there should be, and I also notice that your jar name doesn't have a version number in it. That may be fine for now, but what happens when you put out the next version? They'll clash. Your jar names need to be unique.
> 
> So for now, I'm going to roll this back entirely.

I already updated the jar file in the same release.

2024-10-29 14:53 UTC, ganncamp commented
I'll need a new PR